### ISSUE TITLE
Редактирование статичных страниц

### ISSUE THREAD

**Issue by mikhailborodin** [thinknetica-django-lab-04/cheltsovsv#6]
**Что?**

В модели flatpages есть поле content, оно обычно содержит некий html-текст. Его можно редактировать в админке, но из-за того что это html делать это сложно. Для решения этой проблемы существуют различные wysiwyg-редакторы, Которые дают возможность редактировать текст как в офисных программах, при этом стилистика текста будет сохранена на веб-страницах. Мы будет использовать ckeditor с переопределением админ-класса FlatPageAdmin

**Задача**

1. Установить дополнительно приложение django-ckeditor инструкция по установке и настройке https://github.com/django-ckeditor/django-ckeditor (collectstatic делать не надо, STATIC_ROOT должен быть в .gitignore)
2. В ранее созданном приложении main надо добавить admin.py в нем мы переопределим админ-класс. Чтобы сделать надо сначала сделать unregister модели FlatPage, потом добавить класс FlatPageAdmin в котором будет подключен ckeditor и заново зарегистрировать в админке модель FlatPage с новым FlatPageAdmin

**Ресурсы**

*   https://coderoad.ru/12412170/Django-пользовательские-admin-admin-site-register-admin-site-unregister
* 	https://github.com/django-ckeditor/django-ckeditor
* 	https://docs.djangoproject.com/en/3.1/ref/contrib/admin/

**Comment by cheltsovsv** [comment]
К сожалению, приведенные ресурсы не помогают решить тикет.

Установка ckeditor остановилась на команде pip install, потому что написано, что collectstatic не надо делать, а там больше ничего и не сказано. 

А в пункте №2 написано слишком абстрактно. Пошел гуглить, нашел это https://habr.com/ru/post/340686/, но сервер не запускается с этими штуками:
`    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: django-ckeditor requires                 CKEDITOR_UPLOAD_PATH setting. This setting specifies an                 relative path to your ckeditor media upload directory. Make                 sure you have write permissions for the path, i.e.:                 CKEDITOR_UPLOAD_PATH = 'content/ckeditor/' which                 will be added to SITE_MEDIA/MEDIA_ROOT where needed by storage engine.`

Жду помощи.
